---
agent:
  include:
    # 1.9.9: fd674b8c8b8cf64e9d29f4e8aec198abbc69d127
  exclude:
    - 1.3.3 # burned tag
pe:
  include:
    # 2015.3.2: override_sha
  exclude:
    # - 2015.3.1-1 # burned or faulty tag
